version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    networks:
      - red-app
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.26
    ports:
      - "33006:33006"
    environment:
      - MYSQL_ROOT_PASSWORD = 1234
      - MYSQL_USER = root
      - MYSQL_DATABASE = mysql
    volumes:
      - ~/data/_mysql:/var/lib/mysql
    networks:
      - red-app

  networks:
    red-app:
